### ISSUE TITLE
MatchMaker executable does not have the executable permission (again).

### ISSUE THREAD

**Issue by wdschei** [FIRST-Tech-Challenge/scorekeeper#193]
While testing with [v0.5.2](https://github.com/FIRST-Tech-Challenge/scorekeeper/tree/v0.5.2) this was noticed and after updating to the latest [v0.5.3](https://github.com/FIRST-Tech-Challenge/scorekeeper/tree/v0.5.3) it is the same.

This is the same issue from #34 and the same fix still works.

**Comment by wdschei** [comment]
It's customary to state why an issue was closed. Something like a link to the PR/commit that fixes it, but since this is yet to be fully opened a comment as to the version it was fixed in would be nice.

**Comment by wdschei** [comment]
@adwiii It's customary to state why an issue was closed. Something like a link to the PR/commit that fixes it, but since this is yet to be fully opened a comment as to the version it was fixed in would be nice.

**Comment by adwiii** [comment]
Version before last (0.6.0) we verified that it had the executable permission and that our build process was setting the executable flag for the macOS version of MatchMaker. 

Please let me know if the problem persists and I will look into if there are additional steps we need to take for the build process.

**Comment by tvbarnette999** [comment]
Re-opening, as the problem persists for Linux & Raspberry Pi as of the update to matchmaker. Will fix in next release. For now, use the steps outlined in #34. It should be correct for Macs.

**Comment by adwiii** [comment]
I believe this was resolved some time ago. This can be re-opened if the issue resurfaces.

**Comment by wdschei** [comment]
@adwiii This is definitely fixed in the latest. Thanks.
